title: ZhangWeijie's Homepage
page-top-title: ZhangWeijie
top-section-bg-text: Be what you wanna be
home-subtitle: ZhangWeijie&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; ZhangWeijie 2023-2025. All Rights Reserved.'
